name: base
channels:
  - defaults
dependencies:
  - anaconda-anon-usage=0.7.4=pyhb46e38b_100
  - anaconda-auth=0.10.0=py313haa95532_1
  - anaconda-cli-base=0.6.0=py313haa95532_0
  - anaconda_powershell_prompt=1.1.0=haa95532_1
  - anaconda_prompt=1.1.0=haa95532_1
  - annotated-types=0.6.0=py313haa95532_1
  - archspec=0.2.5=pyhd3eb1b0_0
  - blas=1.0=mkl
  - boltons=25.0.0=py313haa95532_0
  - bottleneck=1.4.2=py313h540bb41_1
  - brotlicffi=1.0.9.2=py313h885b0b7_2
  - bzip2=1.0.8=h2bbff1b_6
  - ca-certificates=2025.12.2=haa95532_0
  - certifi=2025.11.12=py313haa95532_0
  - cffi=2.0.0=py313h02ab6af_1
  - charset-normalizer=3.4.4=py313haa95532_0
  - click=8.1.8=py313haa95532_0
  - colorama=0.4.6=py313haa95532_0
  - conda=25.11.0=py313haa95532_0
  - conda-anaconda-telemetry=0.3.0=pyhd3eb1b0_1
  - conda-anaconda-tos=0.2.2=py313haa95532_1
  - conda-content-trust=0.2.0=py313haa95532_1
  - conda-libmamba-solver=25.4.0=pyhdf14ebd_1
  - conda-package-handling=2.4.0=py313haa95532_1
  - conda-package-streaming=0.12.0=py313haa95532_1
  - cpp-expected=1.1.0=h214f63a_0
  - cryptography=46.0.3=py313habbc9f9_0
  - distro=1.9.0=py313haa95532_0
  - expat=2.7.3=h9214b88_0
  - fmt=11.2.0=h58b7f6e_0
  - frozendict=2.4.6=py313h02ab6af_0
  - idna=3.11=py313haa95532_0
  - intel-openmp=2025.0.0=haa95532_1164
  - jaraco.classes=3.4.0=py313haa95532_0
  - jaraco.context=6.0.0=py313haa95532_0
  - jaraco.functools=4.1.0=py313haa95532_0
  - jsonpatch=1.33=py313haa95532_1
  - jsonpointer=3.0.0=py313haa95532_0
  - keyring=25.6.0=py313haa95532_0
  - libarchive=3.8.2=h6c023e8_0
  - libcurl=8.16.0=h97e0424_0
  - libffi=3.4.4=hd77b12b_1
  - libhwloc=2.12.1=default_hfa10c62_1000
  - libiconv=1.16=h2bbff1b_3
  - libmamba=2.3.2=h7d9f7df_0
  - libmambapy=2.3.2=py313h5078c03_0
  - libmpdec=4.0.0=h827c3e9_0
  - libsolv=0.7.30=h23a355e_2
  - libssh2=1.11.1=h2addb87_0
  - libxml2=2.13.9=h6201b9f_0
  - libzlib=1.3.1=h02ab6af_0
  - lz4-c=1.9.4=h2bbff1b_1
  - markdown-it-py=4.0.0=py313haa95532_0
  - mdurl=0.1.2=py313haa95532_0
  - menuinst=2.4.1=py313h885b0b7_1
  - mkl=2025.0.0=h5da7b33_930
  - mkl-service=2.5.2=py313h0b37514_0
  - mkl_fft=2.1.1=py313hbc2a22c_0
  - mkl_random=1.3.0=py313h42c1672_0
  - more-itertools=10.8.0=py313haa95532_0
  - nlohmann_json=3.11.2=h6c2663c_0
  - numexpr=2.14.1=py313h7660c64_0
  - numpy=2.3.5=py313h050da96_0
  - numpy-base=2.3.5=py313h1e017a8_0
  - openssl=3.0.18=h543e019_0
  - packaging=25.0=py313haa95532_1
  - pandas=2.3.3=py313h42c1672_1
  - pcre2=10.46=h5740b90_0
  - pip=25.2=pyhc872135_1
  - pkce=1.0.3=py313haa95532_0
  - platformdirs=4.5.0=py313haa95532_0
  - pluggy=1.5.0=py313haa95532_0
  - pybind11-abi=5=hd3eb1b0_0
  - pycosat=0.6.6=py313h827c3e9_2
  - pycparser=2.23=py313haa95532_0
  - pydantic=2.12.3=py313haa95532_1
  - pydantic-core=2.41.4=py313h114bc41_0
  - pydantic-settings=2.10.1=py313haa95532_0
  - pygments=2.19.2=py313haa95532_0
  - pyjwt=2.10.1=py313haa95532_0
  - pysocks=1.7.1=py313haa95532_1
  - python=3.13.9=h260b955_100_cp313
  - python-dateutil=2.9.0post0=py313haa95532_2
  - python-dotenv=1.1.0=py313haa95532_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.13=1_cp313
  - pytz=2025.2=py313haa95532_0
  - pywin32-ctypes=0.2.2=py313haa95532_0
  - readchar=4.2.1=py313haa95532_0
  - reproc=14.2.4=hd77b12b_2
  - reproc-cpp=14.2.4=hd77b12b_2
  - requests=2.32.5=py313haa95532_1
  - rich=14.2.0=py313haa95532_0
  - ruamel.yaml=0.18.16=py313hb9a58be_0
  - ruamel.yaml.clib=0.2.14=py313hb9a58be_0
  - semver=3.0.4=py313haa95532_0
  - setuptools=80.9.0=py313haa95532_0
  - shellingham=1.5.4=py313haa95532_0
  - simdjson=3.10.1=h214f63a_0
  - six=1.17.0=py313haa95532_0
  - sqlite=3.51.0=hda9a48d_0
  - tbb=2022.3.0=h90c84d6_0
  - tbb-devel=2022.3.0=h90c84d6_0
  - tk=8.6.15=hf199647_0
  - tomli=2.2.1=py313haa95532_0
  - tqdm=4.67.1=py313h4442805_1
  - truststore=0.10.1=py313haa95532_1
  - typer=0.17.4=py313haa95532_0
  - typing-extensions=4.15.0=py313haa95532_0
  - typing-inspection=0.4.2=py313haa95532_0
  - typing_extensions=4.15.0=py313haa95532_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - urllib3=2.5.0=py313haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py313haa95532_0
  - win_inet_pton=1.1.0=py313haa95532_1
  - xz=5.6.4=h4754444_1
  - yaml-cpp=0.8.0=hd77b12b_1
  - zlib=1.3.1=h02ab6af_0
  - zstandard=0.24.0=py313he335c29_0
  - zstd=1.5.7=h56299aa_0
prefix: C:\Users\shaun\miniconda3
